### ISSUE TITLE
KisekiFS Roadmap  2024 

### ISSUE THREAD

**Issue by crrow** [crrow/kisekifs#8]
# Overview
KisekiFS is a rust learning project, start from Jan. 2024. The basic idea is learning rust itself and associated ecosystem while building a middle-scale fuse file system.

## Details
- [ ] Fuse Client
  - [x] #9
  - [x] Lookup
  - [x] GetAttr
  - [x] SetAttr
  - [x] Readdir
  - [x] Opendir
  - [x] #13
  - [x] #12
  - [x] Create
  - [x] Open
  - [x] Read
  - [x] Write
  - [x] #39
  - [x] #40
  - [x] #41
  - [ ] releasedir
  - [ ] setxattr
  - [ ] getxattr
  - [ ] listxattr
  - [ ] removexattr
  - [ ] getlk
  - [ ] setlk
  - [ ] fallocate
  - [ ] copy_file_range
  - [ ] destroy
- [ ] Optimize start process, get rid of hard-code code
- [ ] Bench
- [ ] Posix Test
- [ ] Meta Backend
  - [ ] TiKV
  - [ ] Etcd
- [ ] CI/CD
  - [ ] Github Actions
  - [x] Home Page
- [ ] Metrics
  -  [ ] fix log tracing
  -  [ ] Prometheus
- [ ] Benchmark
